apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nginxes.mukesh.operator
spec:
  group: mukesh.operator
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    # Aschema is required
    schema:
      openAPIV3Schema:
        type: object
        properties:
          name:
            type: string
          label:
            type: string
  scope: Namespaced
  names:
    plural: nginxes
    singular: nginx
    kind: nginx
    shortNames:
      - nginx